#
# This is kibot configuration.
#
# Edit this file to generate more stuff automatically.
#

kibot:
  version: 1

preflight:
  check_zone_fills: false
  run_erc: false
  run_drc: false

filters:
  - name: lcsc_parts
    type: generic
    include_only:
      - column: 'LCSC Part Number'
        regex: '^C\d+'

outputs:
  - name: print_sch
    type: pdf_sch_print
    options:
      output: 'gen/schematics.pdf'


  - name: pcb_print
    type: pcb_print
    options:
      output: 'gen/pcb.pdf'
      title: "MagLock 2"
      force_edge_cuts: true
      keep_temporal_files: false
      plot_sheet_reference: false
      color_theme: '_builtin_default'
      pages:
        - sheet: 'Assembly'
          scaling: 2
          layers: 
          - layer: F.Mask
            color: '#111111'
          - layer: F.SilkS
            color: '#FFFFFF'

        - sheet: 'Functional Overview'
          layers: [ User.3, User.2 ]
          monochrome: true

        - sheet: 'Power and Fuses'
          layers: [ User.3, User.4 ]
          monochrome: true

        - sheet: 'LED Indicators'
          layers: [ User.3, User.5 ]
          monochrome: true

        - sheet: 'Board Dimensions'
          layers: [ User.8 ]
          monochrome: true

        - sheet: 'Mounting Holes'
          layers: [ User.9 ]
          monochrome: true


  - name: pcb_image_2d_front
    type: pcbdraw
    options:
      output: 'gen/img_pcb_2d_front_bare.jpg'
      format: jpg
      dpi: 300

  - name: pcb_image_2d_back
    type: pcbdraw
    options:
      output: 'gen/img_pcb_2d_back_bare.jpg'
      format: jpg
      dpi: 300
      bottom: true


  - name: pcb_image_3d_main
    type: render_3d
    options:
      output: 'gen/img_pcb_3d_main.png'
      download: true
      rotate_x: 7
      rotate_z: -3
      move_y: 2
      solder_mask: '#104020'
      orthographic: false
      ray_tracing: true
      width: 1200
      height: 1000
      view: top
      zoom: 3

  - name: pcb_image_3d_front
    type: render_3d
    options:
      output: 'gen/img_pcb_3d_front.png'
      orthographic: true
      download: true
      solder_mask: '#104020'
      ray_tracing: true
      width: 1200
      height: 1200
      view: top
      zoom: 3


  - name: ibom_html
    type: ibom
    options:
      output: 'gen/bom_ibom.html'
      no_compression: true
      highlight_pin1: true
      layer_view: F

  - name: full_bom
    type: bom
    options:
      output: 'gen/bom.csv'
      ref_separator: ','
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true

  - name: lcsl_bom
    type: bom
    options:
      output: 'gen/bom_lcsc.csv'
      ref_separator: ','
      exclude_filter: lcsc_parts
      columns:
        - field: 'Quantity Per PCB'
          name: 'Quantity'
        - 'LCSC Part Number'
        - 'Value'
        - 'Footprint'
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true



  - name: JLCPCB_gerbers
    comment: Gerbers compatible with JLCPCB
    type: gerber
    dir: 'gen/gerbers'
    options: &gerber_options
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: true
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      use_protel_extensions: false
      create_gerber_job_file: false
      disable_aperture_macros: true
      gerber_precision: 4.6
      use_gerber_x2_attributes: false
      use_gerber_net_attributes: false
      line_width: 0.1
      subtract_mask_from_silk: true
    layers:
      # Note: a more generic approach is to use 'copper' but then the filenames
      # are slightly different.
      - F.Cu
      - B.Cu
      - Edge.Cuts
      - F.SilkS
      - F.Mask
      - F.Paste
      - B.SilkS
      - B.Mask
      - B.Paste

  - name: JLCPCB_drill
    comment: Drill files compatible with JLCPCB
    type: excellon
    dir: 'gen/gerbers'
    options:
      pth_and_npth_single_file: false
      pth_id: '-PTH'
      npth_id: '-NPTH'
      metric_units: true
      map: gerber
      output: "%f%i.%x"

  - name: JLCPCB
    comment: ZIP file for JLCPCB
    type: compress
    dir: 'gen/gerbers'
    options:
      output: gerbers.zip
      files:
        - from_output: JLCPCB_gerbers
          dest: /
        - from_output: JLCPCB_drill
          dest: /

